.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd May 14, 2012              \" DATE 
.Os "Mac OS X" 10.7
.Dt FSIZE 1      \" Program name and manual section number 
.Sh NAME                 \" Section Header - required - don't modify 
.Nm fsize
.\" Use .Nm macro to designate other names for the documented program.
.Nd Extracts the file size from ls -l
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Ar file
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
is a simple bash script that calls ls -l and extracts the file size (an integer) from the output.  This file size is then printed out.
.Pp                      \" Inserts a space
Parameters:
.Bl -tag -width "file" -compact  \" Begins a tagged list 
.It Ar file              \" Each item preceded by .It macro
The file to get the size of
.El                      \" Ends the list
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "~/Documents/Developer/Scripts/bin    " -compact
.It Pa ~/Documents/Developer/Scripts/bin
fsize    The bash script
.El                      \" Ends the list
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr fsizecomp 1