.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd May 17, 2012               \" DATE 
.Dt openf 1      \" Program name and manual section number 
.Os "Mac OS X" 10.7
.Sh NAME                 \" Section Header - required - don't modify 
.Nm openf
.\" Use .Nm macro to designate other names for the documented program.
.Nd Open the first item in a folder
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
is a bash script that opens the first item in a folder, as returned as ls
.Fl 1
(that is the number one).  It does not have any options.    
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "~/Documents/Developer/scripts/bin    " -compact
.It Pa ~/Documents/Developer/scripts/bin
openf    The bash script
.El
.Sh SEE ALSO 
.Xr rmf 1